Repository bsstayo/GitHub-Summer-Assignment, pull requests merged in 2023-07, with the labels that each got.

#1 [feature] main 프로그램 작성 완료
  test/main.py
Labels: feature

#2 [feature] api 사용해 번호 추출 기능 추가 완료
  .gitignore
  src/extract_number.py
  src/get_api.py
  test/main.py
Labels: feature

#3 README.md 파일을 수정했습니다.
  README.md
Labels: documentation

#4 [feature] feature-main main으로 merge
  .gitignore
  src/extract_number.py
  src/get_api.py
  test/main.py
Labels: feature

#5 [fix]: readme.md 변경
  README.md
Labels: fix

#10 feat: README.md에 두번째 과제 내용 설명 추가
  README.md
Labels: fix

#9 Feature: post-generate-lyric 생성 및 기타 수정
  README.md
  SuperShy.md
  instructions/Week1.md
  instructions/Week2.md
  tools/.gitattributes
  tools/post-generate-lyric.sh
Labels: feature
