Repository bsstayo/GitHub-Summer-Assignment, pull requests merged in 2023-08, with the labels that each got.

#11 Fix readme patch
  README.md
  instructions/Week1.md
  instructions/Week2.md
Labels: fix

#12 Feature phone page
  Andromeda/css/common.css
  Andromeda/css/price.css
  Andromeda/css/product.css
  Andromeda/price.html
  Andromeda/product.html
  Andromeda/src/price.js
  Andromeda/src/product.js
  README.md
  instructions/Week3.md
Labels: feature

#13 [feature] cart.html와 dockerizing 구현
  Andromeda/.gitignore
  Andromeda/Dockerfile
  Andromeda/index.js
  Andromeda/package-lock.json
  Andromeda/package.json
  Andromeda/public/css/cart.css
  Andromeda/public/css/common.css
  Andromeda/public/css/price.css
  Andromeda/public/css/product.css
  Andromeda/public/html/cart.html
  Andromeda/public/html/price.html
  Andromeda/public/html/product.html
  Andromeda/public/images/Android_logo.png
  Andromeda/public/src/cart.js
  Andromeda/public/src/price.js
  Andromeda/public/src/product.js
Labels: feature

#14 Update Week3.md
  instructions/Week3.md
Labels: documentation

#15 Update Week3.md
  instructions/Week3.md
Labels: documentation

#16 [feature] github action 작성
  .github/workflow/melon_chart.yml
  melon/main.py
  melon/requirements.txt
Labels: feature

#17 [feature] action bsstayo
  .github/workflows/melon_chart.yml
  .github/workflows/welcome.yml
  login_welcome/requirements.txt
  login_welcome/welcome.py
Labels: feature

#18 [fix]: requirements.txt 에러 수정
  melon/requirements.txt
Labels: fix

#19 Docs project idea
  docs/final-project-idea.md
Labels: documentation

#22 add link encryptor page demo
  Crypto/index.html
  Crypto/index.js
  Crypto/style.css
Labels: feature
